# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="MicrosoftAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "microsoft_id",
                    models.CharField(
                        max_length=32, verbose_name="microsoft account id"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microsoft_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
