# Generated by Django 2.1.15 on 2021-09-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RdtAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_upd_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rdt_config_dev_stg].[rdt_announcement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RdtLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_datetime', models.DateTimeField()),
                ('log_type', models.CharField(blank=True, max_length=100, null=True)),
                ('application_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(blank=True, max_length=200, null=True)),
                ('source_address', models.CharField(blank=True, max_length=200, null=True)),
                ('source_hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('source_user', models.CharField(blank=True, max_length=200, null=True)),
                ('source_object', models.CharField(blank=True, max_length=500, null=True)),
                ('destination_address', models.CharField(blank=True, max_length=500, null=True)),
                ('destination_hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_user', models.CharField(blank=True, max_length=200, null=True)),
                ('destination_object', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=2000, null=True)),
                ('other', models.CharField(blank=True, max_length=1024, null=True)),
                ('remark', models.CharField(blank=True, max_length=4000, null=True)),
                ('last_upd_date', models.DateTimeField(blank=True, null=True)),
                ('last_upd_by_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rdt_config_dev_stg].[rdt_log',
                'managed': False,
            },
        ),
    ]
